/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-03-14 08:51:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch03;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regofrm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {


    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html><html><head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입 폼 만들기 예제</title>\r\n");
      out.write("<style>\r\n");
      out.write("	h2{border-radius:5px; background-color: wheat; \r\n");
      out.write("	   text-align:center; padding:15px 0;}\r\n");
      out.write("	   \r\n");
      out.write("	#regform{\r\n");
      out.write("	padding:15px 20px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	width:50%;\r\n");
      out.write("	background-color: SandyBrown;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function signup(){\r\n");
      out.write("	 alert(\"정말로 가입하시겠습니까?\");\r\n");
      out.write("	 document.getElementById(\"regform\").style.display=\"none\";\r\n");
      out.write("	 document.getElementById(\"rname\").innerHTML=document.form1.name.value;\r\n");
      out.write("	 document.getElementById(\"remail\").innerHTML=document.form1.email.value;\r\n");
      out.write("	 document.getElementById(\"result\").setAttribute(\"style\",\"display:block; background-color:KhaKi;\");\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>회원 가입</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("<div id=\"regform\">\r\n");
      out.write("	<form name=\"form1\">\r\n");
      out.write("	 <label>이름</label><br>\r\n");
      out.write("	 <input name=\"name\" size=\"40\"><br>\r\n");
      out.write("	 <hr>\r\n");
      out.write("	 <label>이메일</label><br>\r\n");
      out.write("	 <input type=\"email\" name=\"email\" size=\"40\"><br>\r\n");
      out.write("	 <button type=\"button\" onClick=\"signup()\">가입</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"result\" class=\"result\">\r\n");
      out.write("	<h3>가입정보</h3>\r\n");
      out.write("	<hr>\r\n");
      out.write("	이름:<span id=\"rname\"></span><br>\r\n");
      out.write("	이메일:<span id=\"remail\"></span><br>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write(" document.getElementById('result').style.display = \"none\";\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
